export default {
    API_BASE_URL: import.meta.env.VITE_APP_API_BASE_URL ?? "https://ms-evaluation.nexah.net/api/v1",
    APP_BUILD_VERSION: import.meta.env.VITE_APP_BUILD_VERSION ?? "1.0.0",
    APP_ID: import.meta.env.VITE_APP_ID ?? "7b005e5b-405f-11f0-8012-0acc3673109d",
    APP_AUTH_BASE_URL: import.meta.env.VITE_APP_AUTH_BASE_URL ?? "http://localhost:8000/api",
    APP_BASE_URL: import.meta.env.VITE_APP_BASE_URL ?? "https://evaluation-web-admin.dev.nexah.net",
    MS_CRM_API_BASE_URL: import.meta.env.VITE_APP_MS_CMR_BASE_BASE_URL ?? "http://localhost:8000/api",
    MS_SERVICE_API_BASE_URL: import.meta.env.VITE_APP_MS_SERVICE_API_BASE_URL ?? "http://localhost:8000/api",
    MS_VALIDATION_API_BASE_URL: import.meta.env.VITE_APP_MS_VALIDATION_API_BASE_URL ?? "http://localhost:8000/api",
    MS_ORGANISATION_API_BASE_URL: import.meta.env.VITE_APP_MS_ORGANISATION_API_BASE_URL ?? "http://localhost:8000/api",
    MS_EVALUATION_API_BASE_URL: import.meta.env.VITE_APP_MS_EVALUATION_API_BASE_URL ?? "http://localhost:8000/api",
    MS_HR_API_BASE_URL: import.meta.env.VITE_APP_MS_HR_API_BASE_URL ?? "https://ms-rh.nexah.net/api/v1",
    MS_TODO_API_BASE_URL: import.meta.env.VITE_APP_MS_TODO_API_BASE_URL ?? "http://localhost:8000/api",
    APP_NAME: import.meta.env.VITE_APP_NAME ?? "EVALUATION",
    APP_USE_MOCK_API: import.meta.env.VITE_APP_USE_MOCK_API ?? 'false',
    APP_COLOR_PRIMARY_DEFAULT: import.meta.env.VITE_APP_COLOR_PRIMARY_DEFAULT ?? "5EB034",
    APP_COLOR_SECONDARY_DEFAULT: import.meta.env.VITE_APP_COLOR_SECONDARY_DEFAULT ?? "D39C6F",
    APP_LOGO_URL: import.meta.env.VITE_APP_LOGO_URL ?? "https://nxh-pic.s3.us-east-2.amazonaws.com/carrefour-logo.png",
    APP_BACKGROUND_URL: import.meta.env.VITE_APP_BACKGROUND_URL ?? "https://nxh-pic.s3.us-east-2.amazonaws.com/wafa-background.png",
};
