name: stagging-k8-ci

on:
  push:
    branches:
      - "stagging-k8"
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version type to increment (major, minor, patch)"
        required: true
        default: "minor"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "nexah/nnj"
          install: true

      - name: Determine next version
        id: get_version
        run: |
          # Run the script to get the next version
          chmod +x ./increment_version.sh
          version_type=${{ github.event.inputs.version_type || 'patch' }}
          next_version=$(./increment_version.sh $version_type | awk -F= '{print $2}')
          echo "next_version=$next_version" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            nexah/onboarding-web-admin:${{ env.next_version }}
            nexah/onboarding-web-admin:latest
          push: true

      - name: Create Git Tag
        if: github.ref == 'refs/heads/stagging-k8'
        run: |
          git tag ${{ env.next_version }}
          git push origin ${{ env.next_version }}
